# Generated by Django 5.0.4 on 2024-05-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
    ]
